WebApplication1/Controllers/ProjectPortfolioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.DAL;
using WebApplication1.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.IO;

namespace WebApplication1.Controllers
{
    public class ProjectPortfolioController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }
        private ProjectDAL projectContext = new ProjectDAL();
        private StudentDAL studentContext = new StudentDAL();
        private LecturerDAL lecturerContext = new LecturerDAL();

        List<Project> myprojectList = new List<Project>();
        List<ProjectMember> projectmemberList = new List<ProjectMember>();

        public ActionResult ViewProject()
        {

            // GET: Project
            string user = HttpContext.Session.GetString("ID");
            List<ProjectMember> templist = projectContext.GetAllProjectMembers();
            List<Project> projectList = projectContext.GetAllProjects();
            foreach (ProjectMember m in templist)
            {
                if (m.StudentID.ToString() == user)
                {
                    projectmemberList.Add(m);
                }

            }

            foreach (Project p in projectList)
            {
                foreach (ProjectMember m in projectmemberList)
                {
                    if (m.ProjectID == p.ProjectId)
                    {
                        myprojectList.Add(p);
                    }
                }
            }
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Student"))
            {
                return RedirectToAction("Index", "Home");
            }

            return View(myprojectList);



        }
        public ActionResult CreateProject()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateProject(Project project)
        {
            string user = HttpContext.Session.GetString("ID");
            int studentId;
            List<ProjectMember> pmlist = projectContext.GetAllProjectMembers();
            
            if (ModelState.IsValid)
            {
                //Add Project record to database
                project.ProjectId = projectContext.Add(project);
                foreach(ProjectMember projectMember in pmlist)
                {
                    if(projectMember.StudentID.ToString() == user)
                    {
                        studentId = projectMember.StudentID;
                        projectMember.ProjectID = project.ProjectId;
                        projectMember.StudentID = projectContext.Addpm(projectMember);
                        
                        break;
                        
                    }
                }
                
            
                //Redirect user to Project/Index view
                return RedirectToAction("ViewProject");
            }
            else
            {
                //Input validation fails, return to the Create view
                //to display error message
                return View(project);
            }
        }
        public ActionResult Details(int id)
        {
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Student"))
            {
                return RedirectToAction("Index", "Home");
            }
            Project project = projectContext.GetDetails(id);
            ProjectViewModel projectVM = MapToProjectVM(project);
            return View(projectVM);
        }
        public ProjectViewModel MapToProjectVM(Project project)
        {   
            ProjectViewModel projectVM = new ProjectViewModel
            {
                ProjectId = project.ProjectId,
                ProjectTitle = project.Title,
                Description = project.Description,
                ProjectPoster = project.ProjectPoster,
                ProjectURL = project.ProjectURL

            };
            return projectVM;
        }
        public ActionResult UploadPhoto(int id)
        {
            // Stop accessing the action if not logged in
            // or account not in the "Student" role
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Student"))
            {
                return RedirectToAction("Index", "Home");
            }
            Project project = projectContext.GetDetails(id);
            ProjectViewModel projectVM = MapToProjectVM(project);
            return View(projectVM);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UploadPhoto(ProjectViewModel projectVM,Project project)
        {
            if (projectVM.FileToUpload != null &&
            projectVM.FileToUpload.Length > 0)
            {
                try
                {
                    // Find the filename extension of the file to be uploaded.
                    string fileExt = Path.GetExtension(
                     projectVM.FileToUpload.FileName);
                    // Rename the uploaded file with the Project’s name.
                    string uploadedFile = projectVM.ProjectTitle + fileExt;
                    // Get the complete path to the images folder in server
                    string savePath = Path.Combine(
                     Directory.GetCurrentDirectory(),
                     "wwwroot\\images", uploadedFile);
                    // Upload the file to server
                    using (var fileSteam = new FileStream(
                     savePath, FileMode.Create))
                    {
                        await projectVM.FileToUpload.CopyToAsync(fileSteam);
                    }
                    projectVM.ProjectPoster = uploadedFile;
                    project.ProjectId = projectVM.ProjectId;
                    project.ProjectPoster = uploadedFile;
                    projectContext.changephoto(project);
                    ViewData["Message"] = "File uploaded successfully.";
                }
                catch (IOException)
                {
                    //File IO error, could be due to access rights denied
                    ViewData["Message"] = "File uploading fail!";
                }
                catch (Exception ex) //Other type of error
                {
                    ViewData["Message"] = ex.Message;
                }
            }
            return View(projectVM);
        
    }
      

        public ActionResult Edit(int? id)
        {
            List<Student> studentList = lecturerContext.GetAllStudents();
            List<Student> addstudentList = new List<Student>();
            List<SelectListItem> addList = new List<SelectListItem>();
            List<ProjectViewModel> studentinside = new List<ProjectViewModel>();
            List<ProjectMember> projectMemberslist = projectContext.GetAllProjectMembers();
            
            foreach (Student s in studentList)
            {

                addstudentList.Add(s);

            }

            foreach (Student i in addstudentList)
            {
                addList.Add(new SelectListItem
                {
                    Value = i.StudentID.ToString(),
                    Text = i.StudentID.ToString(),
                });


            }

            ViewData["StudentList"] = addList;
            if (id == null) //Query string parameter not provided
            {
                //Return to listing page, not allowed to edit
                return RedirectToAction("Index");
            }

           
            ProjectViewModel project = projectContext.GotDetails(id.Value);
            if (project == null)
            {
                return RedirectToAction("ViewProject");
            }
            return View(project);


        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProjectViewModel project)
        {
            List<ProjectViewModel> port = new List<ProjectViewModel>();

            if (project.ProjectURL == null)
            {
                project.ProjectURL = "";
            }
            //Get branch list for drop-down list
            //in case of the need to return to Edit.cshtml view
            if (ModelState.IsValid)
            {
                //Update Project record to database
                projectContext.Update(project);
                projectContext.Addmember(project);
                return RedirectToAction("ViewProject");
            }
            //Input validation fails, return to the view
            //to display error message
            return View(project);
        }
            public ActionResult ProjectDetails()
        {
            return View();
        }
        public ActionResult CreateResult()
        {
            return View();
        }

    }
}

WebApplication1/Controllers/ViewProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.DAL;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class ProjectController : Controller
    {
        private ProjectDAL staffContext = new ProjectDAL();
        // GET: Project
        public ActionResult Index()
        {
           
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Student"))
            {
                return RedirectToAction("Index", "Home");
            }
            List<Project> projectList = staffContext.GetAllProjects();
            return View(projectList);

        }

        // GET: Project/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Project/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Project/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Project/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Project/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Project/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Project/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApplication1/Views/ProjectPortfolio/CreateProject.cshtml
@model WebApplication1.Models.Project

@{
    ViewData["Title"] = "CreateProject";
    Layout = "~/Views/Shared/_StudentLayout.cshtml";
}

<h4 class="PageTitle">Add Project Portfolio</h4>
<hr />
<form asp-action="CreateProject">
    <fieldset class="FormContent">
        <div class="form-group row">
            <label asp-for="Title"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="Title" class="form-control" required />
                <span asp-validation-for="Title"
                      class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Description"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="Description" class="form-control" required />
                <span asp-validation-for="Description"
                      class="text-danger"></span>
            </div>
        </div>
        <p style="padding:2px 15px;">
            @{
                string userId = "Anonymous";
                string userRole = "Unknown";
                string id = null;
                if (Context.Session.GetString("Role") != null)
                {
                    userRole = Context.Session.GetString("Role");
                }
                if (Context.Session.GetString("Name") != null)
                {
                    userId = Context.Session.GetString("Name");

                }
            }
            PROJECT LEADER:&nbsp;
            <span style="font-weight:bold">@userId </span>
           
        </p>

        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Create"
                       class="btn btn-primary" />
            </div>
        </div>
        <div>
            <a asp-action="ViewProject">Back to List</a>
        </div>
    </fieldset>
</form>

WebApplication1/Views/ProjectPortfolio/Details.cshtml
@model WebApplication1.Models.ProjectViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_StudentLayout.cshtml";
}

<h4 class="PageTitle">View Staff Details</h4>
<hr />
<fieldset class="FormContent">
    <div class="form-group row">
        <div class="form-group row">
            <label asp-for="ProjectPoster" class="col-sm-3 col-form-label"></label>
            <div class="gg">
                <img style="align-content:center;height:auto;width:20%;" src="~/images/@Model.ProjectPoster" />
            </div>
        </div>

        <label asp-for="ProjectId"
               class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9 form-control-plaintext">
            @Html.Display("ProjectId")
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="ProjectTitle" class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9 form-control-plaintext">
            @Html.Display("ProjectTitle")
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Description" class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9 form-control-plaintext">
            @Html.Display("Description")
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="ProjectURL"
               class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9 form-control-plaintext">
            @Html.Display("ProjectURL")
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-9 offset-sm-3">
            <a asp-action="" asp-controller="ProjectPortfolio"
               asp-route-id="@Model.ProjectId">Edit</a> |
            <a asp-action="ViewProject"
               asp-controller="ProjectPortfolio">Back to List</a>
            <a asp-action="UploadPhoto"
               asp-route-id="@Model.ProjectId">Upload Photo</a>
        </div>
    </div>

</fieldset>

WebApplication1/Views/ProjectPortfolio/Edit.cshtml
@model WebApplication1.Models.ProjectViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_StudentLayout.cshtml";
}

<h4 class="PageTitle">Edit Staff Record</h4>
<hr />
<form asp-action="Edit">
    <fieldset class="FormContent">
        <div class="form-group row">
            <label asp-for="ProjectId"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="ProjectId" readonly
                       class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Title"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="Title"
                       class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Description"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="Description" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="ProjectURL"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="ProjectURL"
                       class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="StudentID"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <select asp-for="StudentID"
                        asp-items="@ViewData["StudentList"] as List<SelectListItem>"
                        class="form-control"></select>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Add"
                       class="btn btn-primary" />
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Save"
                       class="btn btn-primary" />
            </div>
        </div>
        <div>
            <a asp-action="ViewProject">Back to List</a>
        </div>
    </fieldset>
</form>

WebApplication1/Views/ProjectPortfolio/UploadPhoto.cshtml
@model WebApplication1.Models.ProjectViewModel

@{
    ViewData["Title"] = "UploadPhoto";
    Layout = "~/Views/Shared/_StudentLayout.cshtml";
}

<h4 class="PageTitle">Upload Staff Photo</h4>
<hr />
<form asp-action="UploadPhoto" enctype="multipart/form-data">
    <fieldset class="FormContent">
        <div class="form-group row">
            <label asp-for="ProjectId"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="ProjectId" readonly
                       class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="ProjectTitle"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="ProjectTitle" readonly
                       class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="ProjectPoster"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9">
                <img style="width:180px;" src="~/images/@Model.ProjectPoster" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="FileToUpload"
                   class="col-sm-3 col-form-label">
                New Photo (jpg format)
            </label>
            <div class="col-sm-9">
                <input asp-for="FileToUpload" accept="image/jpeg" />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Upload"
                       class="btn btn-primary" />
                <span style="color:red;">@ViewData["Message"]</span>
            </div>
        </div>
        <div>
            <a asp-action="ViewProject">Back to List</a>
        </div>
    </fieldset>
</form>

WebApplication1/Views/ProjectPortfolio/ViewProject.cshtml
@model IEnumerable<WebApplication1.Models.Project>

@{
    ViewData["Title"] = "ViewProject";
    Layout = "~/Views/Shared/_StudentLayout.cshtml";
}

<h4 class="PageTitle">View Portfolio</h4>
<p><a asp-action="CreateProject">Create New Portfolio</a></p>
<!-- Add a partial view to display a list of staff records
 in a tabular format. -->
<partial name="~/Views/ProjectPortfolio/_ViewProject.cshtml" model="@Model" />

WebApplication1/Views/ProjectPortfolio/_ViewProject.cshtml
@model IEnumerable<WebApplication1.Models.Project>


    <div class="table-responsive">
        <table id="viewStaff" class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>Project ID</th>
                    <th>Title</th>
                    <th>Project Poster</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.ProjectId.ToString()</td>
                        <td>@item.Title</td>
                        <td>
                            @{ string imageFileName = item.ProjectPoster; }
                            <img src="~/images/@imageFileName"
                                 style="width:50px" />
                        </td>
                        <td>
                            <a asp-action="Edit" asp-controller="ProjectPortfolio"
                               asp-route-id="@item.ProjectId">Edit</a> |
                            <a asp-action="Details" asp-controller="ProjectPortfolio"
                               asp-route-id="@item.ProjectId">Details</a> |
                            <a asp-action="UploadPhoto" asp-controller="ProjectPortfolio"
                               asp-route-id="@item.ProjectId">Upload Poster</a>
                        </td>

                    </tr>
                }
            </tbody>
        </table>
    </div>