WebApplication1/Models/SkillSets.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models
{
    public class SkillSets
    {
        [Display(Name = "SkillSetID")]
        public int SkillSetID { get; set; }

        [Display(Name = "SkillSetName")]
        // Custom Validation Attribute for checking email address exists 
        [ValidateSkillExists(ErrorMessage = "Skill Already Exists!")]
        public string SkillSetName { get; set; }

    }
}

WebApplication1/Models/SkillSetsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models
{
    public class SkillSetsViewModel
    {
        public List<SkillSets> SkillLists { get; set; }
        public List<Student> StudentLists { get; set; }

    }
    
}

WebApplication1/Controllers/SkillSetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;
using WebApplication1.DAL;
using Microsoft.AspNetCore.Http;
using Microsoft.IdentityModel.Protocols;
using System.Data.SqlClient;
using System.Data;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebApplication1.Controllers
{
    public class SkillSetController : Controller
    {
        private SkillDAL skillContext = new SkillDAL();
        private StudentDAL studentContext = new StudentDAL();


        // GET: SkillSet
        public ActionResult Index(int? id)
        {
            if ((HttpContext.Session.GetString("Role") == null) ||
           (HttpContext.Session.GetString("Role") != "Lecturer"))
            {
                return RedirectToAction("Index", "Home");
            }

            ViewData["ViewStudents"] = "";
            SkillSetsViewModel skillVM = new SkillSetsViewModel();
            skillVM.SkillLists = skillContext.GetAllSkill();
            skillVM.StudentLists = new List<Student>();
            // BranchNo (id) present in the query string

            if (id != null)
            {
                ViewData["ViewStudents"] = "Full";
            }
            else
            {
                return View(skillVM);
            }

            List<Student> students = skillContext.GetAllStudentSkillSet(id.Value);
            if (students == null)
            {
                ViewData["ViewStudents"] = "Empty";
                return View(skillVM);
            }

            skillVM.StudentLists = students;
            return View(skillVM);
        }


        // GET: Staff/Edit/5
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if ((HttpContext.Session.GetString("Role") == null) ||
           (HttpContext.Session.GetString("Role") != "Lecturer"))
            {
                return RedirectToAction("Index", "Home");
            }

            SkillSets skillsets = skillContext.GetDetails(id.Value);

            if (skillsets == null)
            {
                //Return to listing page, not allowed to edit                 
                return RedirectToAction("Index");
            }

            return View(skillsets);
        }

        // POST: Staff/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SkillSets skillSets)
        {
            //Get branch list for drop-down list              
            //in case of the need to return to Edit.cshtml view             
            if (ModelState.IsValid)
            {
                //Update staff record to database                 
                skillContext.Update(skillSets);
                return RedirectToAction("Index");
            }

            //Input validation fails, return to the view to display error message             
            return View(skillSets);
        }

        public ActionResult Create()
        {
            //// Stop accessing the action if not logged in or account not in the "Staff" role             
            //if ((HttpContext.Session.GetString("Role") == null) ||
            //    (HttpContext.Session.GetString("Role") != "Staff"))
            //{
            //    return RedirectToAction("Index", "Home");
            //}
            return View();
        }

        // POST: Staff/Create     
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SkillSets skillSets)
        {
            if ((HttpContext.Session.GetString("Role") == null) ||
           (HttpContext.Session.GetString("Role") != "Lecturer"))
            {
                return RedirectToAction("Index", "Home");
            }

            if (ModelState.IsValid)
            {
                //Add staff record to database      
                skillSets.SkillSetID = skillContext.Add(skillSets);
                //Redirect user to Staff/Index view               
                return RedirectToAction("Index");
            }
            else
            {
                //Input validation fails, return to the Create view to display error message                
                return View(skillSets);
            }
        }
        public ActionResult Delete(int? id)
        {
            if ((HttpContext.Session.GetString("Role") == null) ||
                       (HttpContext.Session.GetString("Role") != "Lecturer"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            {
                //Return to listing page, not allowed to edit     
                return RedirectToAction("Index");
            }
            SkillSets skillset = skillContext.GetDetails(id.Value);
            if (skillset == null)
            {
                //Return to listing page, not allowed to edit       
                return RedirectToAction("Index");
            }
            return View(skillset);
        }


        //POST: Skill/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(SkillSets skillSets)
        {
            if ((HttpContext.Session.GetString("Role") == null) ||
           (HttpContext.Session.GetString("Role") != "Lecturer"))
            {
                return RedirectToAction("Index", "Home");
            }

            //Delete skill record from DATABASE
            skillContext.Delete(skillSets.SkillSetID);
            return RedirectToAction("Index");
        }

     
    }
}

WebApplication1/Views/SkillSet/Create.cshtml
@model WebApplication1.Models.SkillSets

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_LecturerLayout.cshtml";
}

<h4 class="PageTitle">Add Staff Record</h4> <hr />
<form asp-action="Create">
    <fieldset class="FormContent">

        <div class="form-group row">
            <label asp-for="SkillSetName" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="SkillSetName" class="form-control" />
                <span asp-validation-for="SkillSetName" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">       
        <div class="col-sm-9 offset-sm-3">   
            <input type="submit" value="Create" class="btn btn-primary" /> 
            </div>       
        </div>


        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    </fieldset>
</form>

WebApplication1/Views/SkillSet/Delete.cshtml
@model WebApplication1.Models.SkillSets

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_LecturerLayout.cshtml";
}

<h4 class="PageTitle">Delete Skill Set</h4> <hr />
<form asp-action="Delete">
    <fieldset class="FormContent">
        <legend>Are you sure to delete this record?</legend>
        <div class="form-group row">
            <label asp-for="SkillSetID" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="SkillSetID" readonly class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="SkillSetName" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="SkillSetName" readonly class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Delete" class="btn btn-primary" />
            </div>
        </div>
        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    </fieldset>
</form>

WebApplication1/Views/SkillSet/Edit.cshtml
@model WebApplication1.Models.SkillSets

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_LecturerLayout.cshtml";
}

<h4 class="PageTitle">Edit Skill Record</h4> <hr />
<form asp-action="Edit">
    <fieldset class="FormContent">
        <div class="form-group row">
            <label asp-for="SkillSetID" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="SkillSetID" readonly class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="SkillSetName" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="SkillSetName" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
            <a asp-action="Index">Back to List</a>
    </fieldset>
</form>

WebApplication1/Views/SkillSet/Index.cshtml
@model WebApplication1.Models.SkillSetsViewModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LecturerLayout.cshtml";
}

<h4 class="PageTitle">View Skill</h4>

<p><a asp-action="Create">Create New Skill</a></p>

    <div class="table-responsive">
        <table id="viewskills" class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>SkillSetID</th>
                    <th>SkillSetName</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.SkillLists)
                {
                    <tr>
                        <td>@item.SkillSetID.ToString()</td>
                        <td>@item.SkillSetName</td>
                        <td>
                            <a asp-action="Edit" asp-controller="SkillSet"
                               asp-route-id="@item.SkillSetID">Edit</a> |
                            <a asp-action="Delete" asp-controller="SkillSet"
                               asp-route-id="@item.SkillSetID">Delete</a> |
                            <a asp-action="Index" asp-controller="SkillSet"
                               asp-route-id="@item.SkillSetID">View Students</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

@{
    if (ViewData["ViewStudents"].ToString() != "")
    {
        if (ViewData["ViewStudents"].ToString() == "Empty")
        {
            <p>No Students have this skillset.</p>
        }

        if (ViewData["ViewStudents"].ToString() == "Full")
        {
            <div class="table-responsive">
                <table class="table table-striped table-bordered">
                    <thead class="thead-dark">
                        <tr>
                            <th>Student ID</th>
                            <th>Name</th>
                            <th>Photo</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var item in Model.StudentLists)
                        {
                        <tr>
                            <td>@item.StudentID</td>
                            <td>@item.Name</td>
                            <td class="studentImg"><img src="~/images/students/@item.Photo" /></td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        }
    }
}